import "./globals.css";
import { Montserrat } from "next/font/google";
import Navbar from "./sections/nav";
import { FooterWithLogo } from "./sections/footer";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Nateq",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon" href="/favicon.svg" />
      <body className={montserrat.className}>
        <Navbar />
        <main>{children}</main>
        <FooterWithLogo />
      </body>
    </html>
  );
}
